version: 2
jobs:
    build:
        docker:
            - image: debian
        steps:
            - checkout
            - run:
                name: install dockerize
                command: curl -O https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                    DOCKERIZE_VERSION: v0.3.0
