version: 2
jobs:
    build:
        docker:
            - image: debian
            - image: circleci/mysql:5.7
        steps:
            - checkout
            - run:
                name: install wget
                command: apt-get update && apt-get install -y wget
            - run:
                name: install mysql client
                command: apt-get update && apt-get install -y mysql-client
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                    DOCKERIZE_VERSION: v0.3.0
            - run:
                name: Connection test
                command: mysql -h 127.0.0.1 -u root -e 'show tables'
