version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Connection test
          command: mysql -h 127.0.0.1 -u root -e 'show tables'
